# Site settings
author: Ghamdan Mohsin
title: Always be open to learn
header-img: img/home-bg.png
email: chemist2ever@gmail.com
copyright_name: Ghamdan Mohsin
description: > # this means to ignore newlines until "baseurl:"
  Think outside the box 
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  gman-code

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
